### ISSUE TITLE
crash when loading singleplayer world, cause- Open Parties and Claims

### ISSUE THREAD

**Issue by Jungl0** [thexaero/open-parties-and-claims#155]
https://bytebin.lucko.me/mRp4pncEaX
this is the link to the crash report, I hope someone can help me and my partner out as we really enjoyed playing on this world and would love to get it back. thanks for any help

**Comment by JakeSuggestions** [comment]
Have you managed to find a solution im going through the exact same problem... let me know if you get any help

Edit: I've been looking around and it seems many people are having this issue and mojang are looking for a fix... seems to be an internal problem... https://twitter.com/MojangStatus/status/1589822938995621888

**Comment by SenanS** [comment]
Exact same issue for me

**Comment by Syber09** [comment]
I'm also having the same problem

**Comment by Purplo262** [comment]
I can confirm I am also having this problem. I am playing the 'Wightcraft' Modpack.

**Comment by Skel-117** [comment]
I am also having this issue and I'm getting the same crash report. I'm playing on the Valhelsia Enhanced Vanilla modpack

**Comment by thexaero** [comment]
I don't know why this would suddenly start happening, unless it's actually related to the vanilla issue. 
Can you check the game log for any errors before this crash?

**Comment by JakeSuggestions** [comment]
> I don't know why this would suddenly start happening, unless it's actually related to the vanilla issue. Can you check the game log for any errors before this crash?

I tried opening up my singleplayer worlds and even creating fresh new ones without the open parties and claims mod, it just gave me an "Invalid Player Data" issue as if the player data files are corrupted... but on a fresh world? Certainly a vanilla issue if you ask me. I dont think mojang would get involved in it otherwise.

**Comment by thexaero** [comment]
@JakeSuggestions Are you still experiencing this? I received some vanilla errors in the logs yesterday when joining worlds but could always play. 

This is such an annoying crash to fix on my end. I know I'm not really obligated to since the cause isn't on my end, but I still want to avoid the confusion.

**Comment by xnosn** [comment]
i just tried playing and can confirm this is still an issue

**Comment by thexaero** [comment]
@xnosn How about now? Mojang have posted that the issue is fixed.

**Comment by JakeSuggestions** [comment]
> @xnosn How about now? Mojang have posted that the issue is fixed.

I'll take a look when I come off work. Hoping it works :/

**Comment by SenanS** [comment]
@thexaero Tried both an old & new world - issue not fixed.
Info:
* Playing Valhelsia Enhanced Vanilla modpack
* [Crash Log](https://bytebin.lucko.me/eXNq9AUUOD)

**Comment by JakeSuggestions** [comment]
> @thexaero Tried both an old & new world - issue not fixed. Info:
> 
> * Playing Valhelsia Enhanced Vanilla modpack
> * [Crash Log](https://bytebin.lucko.me/eXNq9AUUOD)

Getting the exact same crash log. "Ticking Player"
Playing Wightcraft Modpack through Curseforge.

**Comment by thexaero** [comment]
@SenanS What old and new versions? I did not release anything.

**Comment by thexaero** [comment]
Weird... I don't think they fixed it then.

**Comment by thexaero** [comment]
Yeah, people are saying that the issue is back.

**Comment by thexaero** [comment]
@SenanS Here is the actual cause on Valhelsia Enhanced Vanilla. I don't think it's even related to the Mojang issue.
```
Couldn't place player in world
java.lang.NullPointerException: Cannot read the array length because "<local5>" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
	at com.natamus.collective_fabric.functions.DataFunctions.getInstalledModJars(DataFunctions.java:42)
	at com.natamus.collective_fabric.check.RegisterMod.checkIfAllJarsExist(RegisterMod.java:122)
	at com.natamus.collective_fabric.check.RegisterMod.joinWorldProcess(RegisterMod.java:51)
	at com.natamus.collective_fabric.events.CollectiveEvents.onEntityJoinLevel(CollectiveEvents.java:63)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$2(CollectiveFabric.java:31)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:42)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.handler$ddi000$invokeEntityLoadEvent(ServerWorld:1635)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1519)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1480)
	at net.minecraft.server.world.ServerEntityManager.startTracking(ServerEntityManager:210)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:180)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:161)
	at net.minecraft.server.world.ServerWorld.addPlayer(ServerWorld:846)
	at net.minecraft.server.world.ServerWorld.onPlayerConnected(ServerWorld:832)
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:233)
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:130)
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:117)
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$dej000$handlePlayerJoin(ServerLoginNetworkHandler:563)
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:67)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:243)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:918)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by thexaero** [comment]
Seems to be fixed on Collective mod's end: https://github.com/ricksouth/serilum-mc-mods/issues/1413
The modpacks will have to update that though.
EDIT: I can confirm that updating Collective fixes the issue.

**Comment by SenanS** [comment]
> Seems to be fixed on Collective mod's end: [ricksouth/serilum-mc-mods#1413](https://github.com/ricksouth/serilum-mc-mods/issues/1413) The modpacks will have to update that though. EDIT: I can confirm that updating Collective fixes the issue.

+1, My issues are fixed - cheers for being so active @thexaero

**Comment by JakeSuggestions** [comment]
> Seems to be fixed on Collective mod's end: [ricksouth/serilum-mc-mods#1413](https://github.com/ricksouth/serilum-mc-mods/issues/1413) The modpacks will have to update that though. EDIT: I can confirm that updating Collective fixes the issue.

My game finally works! @thexaero you're a blessing! Thank you for all the help and the concern! 
Didn't have to do anything just worked :) 

Works on Wightcraft
👍

**Comment by thexaero** [comment]
No problem :)

**Comment by thexaero** [comment]
Alright, it should now also be fixed on CurseForge's end, so I'll close this.
